name:                haskell-template
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/epoberezkin/haskell-template#readme
license:             BSD3
author:              Evgeny Poberezkin
copyright:           2020 Evgeny Poberezkin
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - classy-prelude

executables:
  haskell-template:
    source-dirs:      src
    main:             Main.hs

ghc-options:
  - -Wall
  - -Wcompat
  - -Worphans
  - -Werror=incomplete-patterns
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wno-name-shadowing
  - -Wredundant-constraints

default-extensions:
  - NoImplicitPrelude
  # numbers, strings, lists
  - NegativeLiterals
  - NumericUnderscores
  - OverloadedStrings
  # function syntax
  - BlockArguments
  - LambdaCase
  # Records
  - DuplicateRecordFields
  - NamedFieldPuns
  - RecordWildCards
  # deriving
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - GeneralisedNewtypeDeriving
  - StandaloneDeriving
  # type classes
  - FunctionalDependencies
  - FlexibleContexts
  - InstanceSigs
  # types
  - DataKinds
  - ConstraintKinds
  - GADTs
  - KindSignatures
  - LiberalTypeSynonyms
  - TypeOperators
